### ISSUE TITLE
bug(swift): nitrogen generate wrong get method in C++, when boolean value with prefix `has`

### ISSUE THREAD

**Issue by wvq** [mrousavy/nitro#648]
### What's happening?

If an boolean property name like `hasXXX`, nitrogen generate `_swiftPart.getHasXXX` in *.hpp.

```typescript
export interface Message extends HybridObject<{ android: 'kotlin'; ios: 'swift' }> {
  msgID: string
  hasRiskContent: boolean
}
```

the generate file is: 
```c++
// HybridMessageSpecSwift.hpp
// ...
    inline bool getHasRiskContent() noexcept override {
      return _swiftPart.getHasRiskContent(); 
    }
// ...
```
build with Xcode 16.2, build error:  
```
No member named 'getHasRiskContent' in 'TIMNativePlugin::HybridMessageSpec_cxx'.
```

the `_swiftPart.getHasRiskContent(); ` should be `_swiftPart.hasRiskContent();`

### Nitro Modules Version

0.25.2

### Nitrogen Version

0.25.2

### Can you reproduce this issue in the Nitro Example app here?

Yes, I can reproduce the same issue in the Example app here

### Additional information

- [ ] I am using Expo
- [x] I am using Nitrogen (nitro-codegen)
- [x] I have read and followed the [Troubleshooting Guide](https://nitro.margelo.com/docs/troubleshooting).
- [x] I created a reproduction PR to reproduce this issue here in the nitro repo. (See [Contributing](https://nitro.margelo.com/docs/contributing) for more information)
- [x] I searched for [similar issues in this repository](https://github.com/mrousavy/nitro/issues) and found none.

**Comment by mrousavy** [comment]
Technically the wrong issue template, but it's fine. 👍

**Comment by mrousavy** [comment]
Fixed in https://github.com/mrousavy/nitro/pull/649; please test it!

**Comment by wvq** [comment]
@mrousavy  that's great
